.circleci/config.yml, crown-court-proceeding/build.gradle, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/CrownCourtOutcome.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/CrownCourtOutcomeTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-218)
Add static data for Crown Court Outcomes.
=> LCAM-218|Add static data for Crown Court Outcomes

crown-court-proceeding/build.gradle
Reverts ministryofjustice/laa-crown-court-proceeding#9
=> Revert "Gradle(deps): Bump info.solidsoft.pitest from 1.7.4 to 1.9.0 in /crown-court-proceeding"

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/CrownCourtProceedingApplication.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/hearing/listener/HearingResultedListener.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecutionconcluded/listener/ProsecutionConcludedListener.java, crown-court-proceeding/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Additional Log Statements

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/CrownCourtProceedingService.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/RepOrderService.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/FullAssessmentResult.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/InitAssessmentResult.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/PassportAssessmentResult.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/controller/CrownCourtProceedingControllerTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/CrownCourtProceedingServiceTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/RepOrderServiceTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/FullAssessmentResultTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/InitAssessmentResultTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/PassportAssessmentResultTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-219)
Migrate business rules for determining the Crown Court Rep Order decision as part of the check crown court actions.
=> LCAM-219|Determine CC Rep Order Decision

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/common/Constants.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/RepOrderService.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/RepOrderServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-220)
Created business rules as per determine_crown_rep_type and associated unit tests.
=> LCAM-220|Migrate business rules for determine_crown_rep_type

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/CrownCourtProceedingService.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/CrownCourtProceedingServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-216)
Migrate business rules from check crown court actions.
=> LCAM-216|Migrate business rules from check crown court actions

crown-court-proceeding/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Remove sentry env variable from application yaml

crown-court-proceeding/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Fix dev deployment - trail 2

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/exception/CCPExceptionHandler.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/exception/ValidationException.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/validation/CrownCourtDetailsValidator.java, crown-court-proceeding/src/main/resources/schemas/common/apiCrownCourtOutcome.json, crown-court-proceeding/src/main/resources/schemas/common/apiCrownCourtSummary.json, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/validation/CrownCourtDetailsValidatorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-225)
- Added crown court outcome validation, exception handler, unit tests
- Update json schema with outcome fields
=> Lcam 225 check cc details

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/staticdata/enums/CaseType.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-496)
Fix json parse error.
=> LCAM-496|Fix json parse error

crown-court-proceeding/src/main/resources/schemas/apiProcessRepOrderRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-497
Update schema to remove commitalDate from required fields.
=> LCAM-497|Update schema to remove commitalDate from required fields

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/ProceedingService.java, crown-court-proceeding/src/main/resources/schemas/apiProcessRepOrderRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-505)
Update schema to remove Mag Court Outcome from required fields list.
=> LCAM-505|Mag Court Outcome is not a required field

crown-court-proceeding/Dockerfile
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-508)
Updated docker base image
=> LCAM-509| updated base image

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-501)
- Consolidated build and test job into one.
- Removed unused and old orbs
- Clean up
=> Lcam 501 refactor pipeline

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/controller/CrownCourtProceedingController.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/ProceedingService.java, crown-court-proceeding/src/main/resources/schemas/apiUpdateApplicationResponse.json, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/controller/CrownCourtProceedingControllerTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/controller/CrownCourtProceedingIntegrationTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/ProceedingServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-529)
Fix the broken integration between MAAT & CCP, the update application end point should return the modified date time.
=> Lcam 529 maat ccp integration

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-507)
Updated helm orb with helm commands
=> LCAM-507| replaced legacy helm orb with commands

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/builder/UpdateRepOrderDTOBuilder.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/dto/maatcourtdata/RepOrderDTO.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/ProceedingService.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/RepOrderService.java, crown-court-proceeding/src/main/resources/schemas/apiUpdateApplicationResponse.json, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/builder/UpdateRepOrderDTOBuilderTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-531)
Issue fixed for RepOrderDecision and RepOrderDate missing
=> LCAM-531-assessment failing in CCP Route

crown-court-proceeding/src/main/resources/schemas/apiUpdateApplicationRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-616)
=> LCAM-616-remove-payment-field

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/builder/CrownCourtDTOBuilder.java, crown-court-proceeding/src/main/resources/schemas/apiUpdateApplicationRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-616)
Schema Mapping 
=> LCAM-616-cc-integration

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/MaatCourtDataService.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/MaatCourtDataServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-616)
Changed to POST call
=> LCAM-616-post-api-change

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/ProceedingService.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/ProceedingServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LLCAM-676)
changes made for cc details validation 
=> LCAM-676-cc validation 

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/builder/UpdateApiResponseBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)
=> Null Check

.circleci/config.yml, crown-court-proceeding/Dockerfile
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-636)
Changes made for short lived credentials
=> Lcam 636 short lived credentials

crown-court-proceeding/.snyk
[LCAM-859](https://dsdmoj.atlassian.net/browse/LCAM-859)
- Removed snyk ignore for Spring framework security
[LCAM-859]: https://dsdmoj.atlassian.net/browse/LCAM-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LCAM 859: Removed snyk ignore for Spring framework security

crown-court-proceeding/src/main/resources/db/changelog/changeset/10-recreate-prosecution-concluded-table.sql, crown-court-proceeding/src/main/resources/db/changelog/db.changelog-master.yaml
Recreated prosecution_concluded table to fix PROD issue
=> Recreate prosecution_concluded table to fix PROD issue

.github/PULL_REQUEST_TEMPLATE.md, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/builder/CrimeEvidenceBuilder.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/CrimeEvidenceDataService.java, crown-court-proceeding/src/main/resources/schemas/apiCalculateEvidenceFeeRequest.json, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/builder/CrimeEvidenceBuilderTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1004)
Removed laaTransactionId from the calculate evidence fee request.
Updated PR template to reflect the Jira naming.
=> LCAM-1004|Remove laaTransactionId

crown-court-proceeding/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-XXX)
=> Fixed Synk Vulnerability

crown-court-proceeding/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-XXX)
=> Upgrade Sentry Version

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/builder/UpdateRepOrderDTOBuilder.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/dto/maatcourtdata/UpdateRepOrderRequestDTO.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1132)
=> LCAM-1132-Remove IOJ type and code

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/builder/CrownCourtDTOBuilder.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/dto/CrownCourtDTO.java, crown-court-proceeding/src/main/resources/schemas/apiProcessRepOrderRequest.json, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/builder/CrownCourtDTOBuilderTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1256)
=> LCAM 1256 Remove laaTransactionId from Schemas

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/builder/CrownCourtDTOBuilder.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/builder/CrownCourtDTOBuilderTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1262)
Added Null check on decisionDate field, before converting to local date.
=> Null check before converting to local date

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/scheduler/ProsecutionConcludedScheduler.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1323)
=> LCAM-1323-update-scheduler-table

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/scheduler/ProsecutionConcludedScheduler.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/scheduler/ProsecutionConcludedSchedulerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/Lcam 1323)
Update retry count when case concluded but haven't received hearing result  
=> Lcam -1323-update-retry-count

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1538)
CircleCI integration with slack for deployment and build notifications as detailed in this tutorial https://circleci.com/docs/slack-orb-tutorial/
=> LCAM-1538|CircleCI and Slack integration for deployment notifications

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/CrimeEvidenceDataService.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/MaatCourtDataService.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-XXX)
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> Added log statements to log the request

helm_deploy/laa-crown-court-proceeding/values-dev.yaml, helm_deploy/laa-crown-court-proceeding/values-prod.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4092)
Update the MAAT Data API url to point to CP in development environment.
=> LASB-4092|Update the MAAT Data API url to point to CP in Dev

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/helper/CalculateOutcomeHelper.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/model/OffenceSummary.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/scheduler/ProsecutionConcludedScheduler.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/service/ProsecutionConcludedService.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/helper/CalculateOutcomeHelperTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/listener/ProsecutionConcludedListenerTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/scheduler/ProsecutionConcludedSchedulerTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/service/ProsecutionConcludedServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3940)
Git not allowed to revert back the PR LASB-3940(https://github.com/ministryofjustice/laa-crown-court-proceeding/pull/237)
This PR to manually revert back  changes. 
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> LASB-3940-revert-changes

crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/scheduler/PurgeProsecutionConcludedScheduler.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/repository/QueueMessageLogRepository.java, crown-court-proceeding/src/main/java/uk/gov/justice/laa/crime/crowncourt/service/QueueMessageLogService.java, crown-court-proceeding/src/main/resources/application.yaml, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/data/builder/TestModelDataBuilder.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/prosecution_concluded/scheduler/PurgeProsecutionConcludedSchedulerTest.java, crown-court-proceeding/src/test/java/uk/gov/justice/laa/crime/crowncourt/service/QueueMessageLogServiceTest.java, crown-court-proceeding/src/test/resources/application.yaml, crown-court-proceeding/src/testSqsIntegration/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/LSAB-4452)
New scheduler to purge queue message log table and run once a day at 2AM
2 month old record should deleted   
- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.
=> LSAB-4452-purge-queue-log-table
